SET foreign_key_checks = 0;
DROP TABLE IF EXISTS hardware;
DROP TABLE IF EXISTS software;
DROP TABLE IF EXISTS internal_specialist;
DROP TABLE IF EXISTS external_specialist;
DROP TABLE IF EXISTS analyst;
DROP TABLE IF EXISTS problem_type;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS operating_system;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS solution;
DROP TABLE IF EXISTS ticket_solution;
DROP TABLE IF EXISTS handler;
DROP TABLE IF EXISTS dropped;
DROP TABLE IF EXISTS skillset;
SET foreign_key_checks = 1;